### ISSUE TITLE
关于说明文档，这么写是不是更有看点一些

### ISSUE THREAD

**Issue by rijieli** [ming1016/HTN#1]
原先的版本太含糊了，读完前言根本不明白项目介绍了什么，我建议给文档加一句。下面加粗部分是我写的，可能不太准确，不过我觉得有必要开头点名项目存在的意义，您觉得如何呢

**HTN 是一个将HTML 转换为原生Swift 和 Objective-C组件的项目**，本文主要是记录 HTN 项目开发的过程。关于这个项目先前在 Swift 开发者大会上我曾经演示过，不过当时项目结构不完善，不易扩展，也没有按照标准来。所以这段时间，我研究了下 W3C 的标准和 WebKit 的一些实现，对于这段时间的研究也写了篇文章深入剖析 WebKit。重构了下这个项目，我可以先说下已经完成的部分，最后列下后面的规划。项目已经放到了 Github 上：https://github.com/ming1016/HTN 后面可以对着代码看。

**Comment by ming1016** [comment]
不错，这样开头会很清晰。我改下
